#-----------------------------------------------------------------
# Use this file to add customized Bnd instructions for the bundle
#-----------------------------------------------------------------

Bundle-Activator: ${bundle.namespace}.internal.InitActivator
Import-Package:cn.com.rexen.core.api.biz,cn.com.rexen.core.api.persistence,<packageName>.entities,*
Bundle-Category: Rexen  <projectName> <beanName>