\<?xml version="1.0" encoding="UTF-8"?>
\<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    \<modelVersion>4.0.0\</modelVersion>

    \<parent>
        \<groupId><packageName>\</groupId>
        \<artifactId><pomName>-parent\</artifactId>
        \<version><versionName>\</version>
    \</parent>

    \<artifactId><pomName>-rest\</artifactId>
    \<packaging>bundle\</packaging>
    \<name><projectName> :: <beanName> - Rest\</name>
    \<description><beanName> Rest Service\</description>

    \<properties>
        \<bundle.symbolicName><packageName>.rest\</bundle.symbolicName>
    \</properties>
\</project>